name: runo_live
description: Lummy Party App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  lottie: any
  # SVGA ÇÖPE ATILDI!
  video_player: any
  pag: any
  audioplayers: any
  http: any
  livekit_client: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # İleride test edeceğimiz WebM ve PAG klasörlerini aktif tutabiliriz
    - v2/assets/animations/mp3/
    - v2/assets/animations/png/
    #- assets/animations/pag/
    #- assets/animations/webm/