name: runo_live
description: Runo Live sosyal eglence uygulamasi.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # ÇOKLU FORMAT MOTORLARIMIZ (Eksiksiz Liste)
  lottie: any
  svgaplayer_flutter: any
  video_player: any
  pag: any  # YENİ: Tencent PAG Motoru Eklendi!
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/svga/
    
    # DİKKAT: İçi boş olan klasörleri '#' ile gizledik. 
    # İçlerine dosya atınca başındaki '#' işaretini silebilirsin.
    #- assets/animations/pag/
    #- assets/animations/lottie/
    #- assets/animations/webm/
    #- assets/animations/png/